"""empty message

Revision ID: 551537452ab5
Revises: 3e712614d056
Create Date: 2019-10-03 11:08:16.412585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '551537452ab5'
down_revision = '3e712614d056'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=True),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('vendorName', sa.String(length=64), nullable=True),
    sa.Column('vendorLocation', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column(u'users', 'cardNum',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column(u'users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column(u'users', 'firstName',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column(u'users', 'lastName',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['cardNum'])
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column(u'users', 'lastName',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column(u'users', 'firstName',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column(u'users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column(u'users', 'cardNum',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('transactions')
    # ### end Alembic commands ###
