"""empty message

Revision ID: d24360be54f8
Revises: 551537452ab5
Create Date: 2019-10-03 11:38:57.985010

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd24360be54f8'
down_revision = '551537452ab5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column(u'transactions', 'amount',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column(u'transactions', 'category',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column(u'transactions', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column(u'transactions', 'userID',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column(u'transactions', 'vendorLocation',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column(u'transactions', 'vendorName',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.create_foreign_key(None, 'transactions', 'users', ['userID'], ['id'])
    op.create_foreign_key(None, 'transactions', 'categories', ['category'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.alter_column(u'transactions', 'vendorName',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column(u'transactions', 'vendorLocation',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column(u'transactions', 'userID',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column(u'transactions', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column(u'transactions', 'category',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column(u'transactions', 'amount',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_table('categories')
    # ### end Alembic commands ###
